### ISSUE TITLE
Gas laws of physics

### ISSUE THREAD

**Issue by ShyamSunder149** [nilis24/physics.h#12]
Implementation of Gas laws with physics

Will contain:
Boyle's law
charle's law
avagadro law
ideal gas law

**Comment by nilis24** [comment]
assigned!

**Comment by ShyamSunder149** [comment]
Thanks!

**Comment by WaniAthar** [comment]
can i help you with this? @ShyamSunder149

**Comment by nilis24** [comment]
@WaniAthar only one person for issue sorry

**Comment by Fonta22** [comment]
Merged https://github.com/nilis24/physics.h/pull/42.
