### ISSUE TITLE
Newton's Laws

### ISSUE THREAD

**Issue by Fonta22** [nilis24/physics.h#2]
**Is your feature request related to a problem? Please describe.**
Adding the Newton's Laws to the project.

**Describe the solution you'd like**
A part of the package that would calculate the Newton's Laws.

**Describe alternatives you've considered**
There are no alternatives, at is just a new feature.

**Additional context**
![image](https://user-images.githubusercontent.com/61181201/193090330-ea57e90d-7c47-42a3-8680-26d77a95eb74.png)
👍🏻

**Comment by Arghya-Banerjee** [comment]
I can create Newton's Laws calculations in C++ for you. Please assign me this issue

**Comment by nilis24** [comment]
@Arghya-Banerjee you have to create your own issue to be assigned to it. So this issue will be assigned to @Fonta22

**Comment by Fonta22** [comment]
PR done and merged.
