### ISSUE TITLE
Missing contributing.md file

### ISSUE THREAD

**Issue by RathoreAbhiii** [nilis24/physics.h#20]
This repository is missing a contributing.md file. Every repo listed for hacktoberfest needs to have a contributing.md file in order to be able to accept contributions for hacktoberfest 2022. 
You can assign me this issue. I can add the file with relevant information.

**Comment by nilis24** [comment]
Hi! @RathoreAbhiii sorry there is a contributing.md file yet but I don't realise that contributors can find it because is in the .github directory. Sorry, I will fix this up now
