### ISSUE TITLE
Solve error in gravitation.h

### ISSUE THREAD

**Issue by Fonta22** [nilis24/physics.h#21]
There's an error in **gravitation.h** file, in the **GravitationalPotentialCircularDisc** function, line `24`.
```c
package/gravitation/gravitation.h:24:33: error: expected identifier before numeric constant
   24 |     return -2 * G * m / (pow(t. 0.5) * pow(r, 2));
      |                                 ^~~
```

If someone can fix it, please ask to be assigned to this issue, and **after**, create a **Pull Request**.

**Comment by RathoreAbhiii** [comment]
Hey, I would like to work on this issue! Can you please assign it to me?

**Comment by nilis24** [comment]
Yes! assigned to you @RathoreAbhiii

**Comment by Fonta22** [comment]
Also, there's another error in the **AccelarationDuetoGravity** function, as it uses 2 arguments and not 3.
```c
double AccelarationDuetoGravity(double m, double r, double) {
    return G * m / pow(r, 2);
}
```
(Should remove that `double` without value)

**Comment by RathoreAbhiii** [comment]
Will check that as well.

**Comment by Fonta22** [comment]
Perfect, thanks.

**Comment by RathoreAbhiii** [comment]
@Fonta22 Done with this issue! Please review the PR and merge it if it is okay or suggest changes as soon as you can. Thanks!

**Comment by Fonta22** [comment]
https://github.com/nilis24/physics.h/pull/37 Merged, thanks!
