### ISSUE TITLE
Quantum Mechanics

### ISSUE THREAD

**Issue by Antibodyy** [nilis24/physics.h#26]
I will start by adding :
1. Photoelectric effect
2. Wien's Law
3. Stefan Boltzmann Law
4. Heisenberg's Uncertainty Principle,
and so on.
Lots to add to this potentially in the future as well

**Comment by nilis24** [comment]
Hi, @Antibodyy. Okay, I will assign it to you. Put your code in ./package/quantum_mechanics/quantum_mechanics.h
