### ISSUE TITLE
Laws of Gravitation

### ISSUE THREAD

**Issue by Arghya-Banerjee** [nilis24/physics.h#3]
**Is your feature request related to a problem? Please describe.**

Adding Laws of Gravitation calculations to physics.h

**Describe the solution you'd like**

It would help calculate the value for gravitational force, gravity would contain some universal constants.

**Describe alternatives you've considered**

No alternatives, it's unique.

**Additional context**

[About Gravitational Laws and formulas](https://www.vedantu.com/formula/important-gravitation-formulas-for-jee)

This can be used as a reference

Assign me this issue so that I can work on this starting immediately.

**Comment by nilis24** [comment]
Hi @Arghya-Banerjee now yes, I will assign this issue to you. Thanks

**Comment by nilis24** [comment]
Please follow the structure of the project that I make
