### ISSUE TITLE
Want to contribute something

### ISSUE THREAD

**Issue by YashAdake** [nilis24/physics.h#33]
I am very new to open source. I also wanted to contribute to this to complete my hacktoberfest challenge. I can write basic programs for formulas or also I would like to create text documents explaining concepts of physics. Please allow me to do so...

**Comment by nilis24** [comment]
Hi, if  you want to contribute to a repo, the first thing that you have to do is to read and follow contributing.md file. You just created this issue and make a pr without following the contributing guidelines.
