### ISSUE TITLE
Modern Physics 

### ISSUE THREAD

**Issue by Adhiraj-11** [nilis24/physics.h#39]
I will include a new folder named modern physics including formulas for 
 - photoelectric effect 
      - photons energy
      - photons momentum
      - de Broglie wavelength
 - The bhors Atom
      - Energy in nth Bohr’s orbit
      - Radius of the nth Bohr’s orbit

**Comment by Fonta22** [comment]
Cool, thanks!

**Comment by Adhiraj-11** [comment]
made the PR.

**Comment by Fonta22** [comment]
Will be reviewed soon
