### ISSUE TITLE
Laws of optics

### ISSUE THREAD

**Issue by nilis24** [nilis24/physics.h#4]
**Is your feature request related to a problem? Please describe.**
computationally calculate the laws of optics in C

**Describe the solution you'd like**
Code the laws of optics in optics.h

**Comment by sasidharswarangi** [comment]
I would like to work on this issue

**Comment by nilis24** [comment]
assigned! @sasidharswarangi

**Comment by sasidharswarangi** [comment]
created a pull request, please review it #29
