### ISSUE TITLE
Add Kirchoff's law, Power formula  

### ISSUE THREAD

**Issue by Sukriti-m** [nilis24/physics.h#51]
Add Kirchoff's law, Power formula, star to delta and vice-versa connection formulas in this repo.

This issue is up for grab, anyone interested can tag the owner and get it assigned.

**Comment by nilis24** [comment]
Hi, @Sukriti-m. The only people that can create issues and then leave them free to be assigned to anyone is the owner (me) and admins (@Fonta22), so you have no right to say what you said.

**Comment by Sukriti-m** [comment]
> Hi, @Sukriti-m. The only people that can create issues and then leave them free to be assigned to anyone is the owner (me) and admins (@Fonta22), so you have no right to say what you said.

I apologize I wasn't aware of it. I'll just close this issue then.
